# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.box_url = "debian/jessie64"

  config.vm.network "private_network", ip: "10.0.0.100"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "CDSServer"
    vb.cpus = 2
    vb.memory = 1024
    #vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
    ansible.ask_sudo_pass = true
  end

end
