---
  - name: install general configuration
    hosts: all
    remote_user: root
    roles:
      - common

  - name: install development tools
    hosts: dev
    remote_user: root
    roles:
      - dev
